apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-credit-config
  namespace: demo-credit
  labels:
    app.kubernetes.io/name: demo-credit
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "*"

  DB_HOST: "demo-credit-mysql"
  DB_PORT: "3306"
  DB_NAME: "democredit"

  JWT_EXPIRES_IN: "7d"
  ADJUTOR_BASE_URL: "https://adjutor.lendsqr.com/v2"
