# Replace the placeholder values after `terraform apply`:
# - <KEY_VAULT_NAME> from `terraform output key_vault_name`
# - <TENANT_ID> from `terraform output tenant_id`
# - <KEY_VAULT_CSI_CLIENT_ID> from `terraform output key_vault_csi_client_id`
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-credit-keyvault-secrets
  namespace: demo-credit
  labels:
    app.kubernetes.io/name: demo-credit
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "6738eb89-0854-4ae8-8606-a67ead8f1c42"
    keyvaultName: "kv-democredit-6ho4np"
    tenantId: "c69f3e39-8601-43c0-b0a6-115746c7f8c6"
    objects: |
      array:
        - |
          objectName: DB-USER
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: ADJUTOR-API-KEY
          objectType: secret
  secretObjects:
    - secretName: demo-credit-secrets
      type: Opaque
      data:
        - objectName: DB-USER
          key: DB_USER
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: JWT-SECRET
          key: JWT_SECRET
        - objectName: ADJUTOR-API-KEY
          key: ADJUTOR_API_KEY
